# Generated by Django 4.1.5 on 2023-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
